### ISSUE TITLE
Add another shortcut to start Big Picture in high resolution mode

### ISSUE THREAD

**Issue by b-** [aaronfranke/Steam-Big-Picture-Shortcut#2]
I’m mostly just leaving this here to remind myself; I’ll probably create another pull request with a second set of shortcuts later after I get home.

But anyway, if you append the flag `-fulldesktopres` to the Steam command line, Big Picture will render at the native resolution of the display. Without this flag it caps out at 1080p, so this makes the Big Picture menu look loads better on, e.g., 4K displays.

**Comment by aaronfranke** [comment]
Feature added with https://github.com/aaronfranke/Steam-Big-Picture-Shortcut/pull/3, closing.
